version: 2
updates:
- package-ecosystem: npm
  directory: '/'
  ignore:
    # This is pinned to an older version based on the consumed VS Code APIs
    - dependency-name: '@types/vscode'
  schedule:
    interval: weekly
    day: wednesday
    time: '12:00'
  open-pull-requests-limit: 20
  labels:
  - dependencies
